### ISSUE TITLE
Start Dates

### ISSUE THREAD

**Issue by samwoodzadrot** [simsulla/min.simsulla.org#2]
Hello. I think it would be good if it was in mod scenario in 2013-2017 years.

**Comment by simsulla** [comment]
I understand why you would like a 2017 start (I would too) but one need to way-in the benefit from the effort. 
And actually we are contemplating the opposite, only having one start date 1946. It is a lot of work to maintain several start dates. Will change the issue title as a more generic "Start Dates".
